### ISSUE TITLE
Picture in .jpg format

### ISSUE THREAD

**Issue by jerryandtom007** [nemec/thumbsheet#1]
Hello, how can I make the picture in .jpg format clearer?

**Comment by nemec** [comment]
Hello, can you give an example of unclear results?

The tool resizes each thumbnail to fit within the grid, which may cause some fuzziness depending on the size of the original media and the number of items in the grid. One option to try is to set the width of the resulting image manually - instead of the default 1024, try 4096. This will make each thumbnail 4x as large, but will also increase the file size of the resulting thumbsheet.

    python3 thumbsheet.py -w 4096 '~/vid/*.mp4'

**Comment by jerryandtom007** [comment]
Hello, thank you for your reply.
I use'thumbsheet' and'vcsi' to output thumbnails with a size of 1024_(4x4).jpg respectively.
The output file size of thumbsheet is 116KB. The output file size of vcsi is 211KB.
The jpg file of'thumbsheet' is a little fuzzy. There is an option of ‘DEFAULT_IMAGE_QUALITY = 100’ in vcsi to customize the quality of the output image. Can this option be added to the 'thumbsheet'? I don't understand that the python language may be very troublesome. It's okay. This is just a suggestion. The thumbnails output by the'thumbsheet' look beautiful, and I like it.

**Comment by nemec** [comment]
Hello, now that I've had some time to revisit the code, I don't think this will be possible. Unless you've modified the code, Thumbsheet writes a PNG file while vcsi outputs to JPEG. The PNG format does not have a "quality" setting like JPEG does (due to differences in the algorithm, it doesn't need it), so even though I could add a quality filter it would not change the output.

I see in the vcsi codebase that it has a "smart" algorithm to choose the least blurry frames for its thumbnail selection, which I believe is why you see the difference. It's a very cool idea, but it looks like a lot of work that I unfortunately do not have time/interest to copy. Sorry!

I do appreciate your comments, though. Thanks for using the program 😊
